Repository CSC207-2023Y-UofT/course-project-monopoly, pull requests merged in 2023-08, with the labels that each got.

#60 [54] Added tests for GameController and InitController
  data/test/destiny_card_chance_test.csv
  data/test/destiny_card_chest_test.csv
  data/test/extra_blocks_test.csv
  data/test/properties_test.csv
  src/main/java/controller/GameController.java
  src/main/java/entity/Player.java
  src/main/java/useCases/OwnerPropertyUseCase.java
  src/main/java/useCases/impactor/StatusImpactor.java
  src/test/java/controller/GameControllerTest.java
  src/test/java/controller/InitControllerTest.java
Labels: documentation, enhancement

#69 Rewrite the README.md
  README.md
Labels: documentation

#61 [55] Added PropertyTest
  data/test/properties_test.csv
  src/main/java/Main.java
  src/main/java/entity/Block.java
  src/main/java/entity/Property.java
  src/main/java/presenters/OutputPresenter.java
  src/main/java/presenters/PlayerInfoPanel.java
  src/main/java/useCases/OwnerIdentifier.java
  src/main/java/useCases/OwnerPropertyUseCase.java
  src/main/java/useCases/PasserbyUseCase.java
  src/main/java/useCases/generator/PropertyGenerator.java
  src/main/java/useCases/generator/RevisedPropertyGenerator.java
  src/main/java/useCases/impactor/PropertyImpactor.java
  src/test/java/entity/PropertyTest.java
  src/test/java/useCases/OwnerIdentifierTest.java
  src/test/java/useCases/OwnerPropertyUseCaseTest.java
  src/test/java/useCases/PasserbyUseCaseTest.java
  src/test/java/useCases/generator/DestinyCardPoolGeneratorTest.java
  src/test/java/useCases/generator/GeneratorTest.java
  src/test/java/useCases/generator/PropertyGeneratorTest.java
Labels: documentation, enhancement

#72 Create data gateway for generators
  src/main/java/datagateways/DataManager.java
  src/main/java/datagateways/DestinyCardDataManager.java
  src/main/java/datagateways/PropertyDataManager.java
  src/main/java/useCases/generator/DestinyCardPoolGenerator.java
  src/main/java/useCases/generator/PropertyGenerator.java
Labels: enhancement

#101 Game board cleanup
  src/main/java/Main.java
  src/main/java/presenters/GameBoard.java
  src/main/java/presenters/OutputPresenter.java
Labels: enhancement
